### ISSUE TITLE
RetrieveFile get bytes or reader

### ISSUE THREAD

**Issue by andrexus** [marcobeierer/ftps#2]
I just want to load the file in memory and not store it on disk. Is it possible to get just bytes array or reader?

**Comment by marcobeierer** [comment]
Currently this is not supported, but it wouldn't be much work to implement it. 

[RetrieveFile](https://github.com/marcobeierer/ftps/blob/master/ftps.go#L330) calls `requestDataConn` which returns a `net.Conn` which implements the `Reader` interface.

I have currently not the time to implement and especially test this, but I'm open for pull requests.

**Comment by marcobeierer** [comment]
Thank you, I have merged your pull request and added some error checking for `buf.ReadFrom()`
